title: Microbial Eukaryotes
author: Philippe Silar
description: An online version of the book Protistes Eucaryotes - Origine, Evolution et Biologie des Microbes Eucaryotes by Philippe Silar translated to English.
baseurl: "/Microbial-eukaryotes" # the subpath of your site, e.g. /blog
url: "//markhilt.github.io" # the base hostname & protocol for your site
github_username:  markhilt

# Build setup:
markdown: kramdown
theme: minima
plugins:
  - jekyll-seo-tag
