title: Microbial Eukaryotes
author: Markus Hiltunen, Mahwash Jamy, Fabien Burki & Hanna Johannesson
description: >
  An e-book about the evolution and diversity of microbial eukaryotes including fungi.
baseurl: "/Microbial-eukaryotes" # the subpath of your site, e.g. /blog
url: "//markhilt.github.io" # the base hostname & protocol for your site

# Build setup:
markdown: kramdown
theme: minima
plugins:
  - jekyll-seo-tag
